[build]
  base = "client/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[[redirects]]
  from = "/api/*"
  to = "https://server-eight-alpha-56.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_ENV = "production"
  REACT_APP_API_URL = "https://server-eight-alpha-56.vercel.app"

[context.deploy-preview.environment]
  REACT_APP_ENV = "staging"
